version: '3.7'

services:
  mysql:
    image: mysql:5.7.16
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=notes_testing
    volumes:
      - ./data/testing:/var/lib/mysql
    ports:
      - '13306:3306'

  redis:
    image: 'redis:4'
    ports:
      - '16379:6379'
